"""rename department

Revision ID: 20a30f8c9de7
Revises: 89fa9ac2579a
Create Date: 2024-10-19 15:23:23.493723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a30f8c9de7'
down_revision = '89fa9ac2579a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###